Translations
imaginerio/narratives pull request #81
Opened 2022-04-15 14:13 UTC by davidheyman

Locale support and translations

2022-04-15 16:01 UTC, buccalon commented on src/pages/index.js
> +  } = await axios.get(`${process.env.NEXT_PUBLIC_PAGE_URL}${locale}-narratives-about/96.json`, {
Portuguese version has a different url: https://forum.imaginerio.org/t/pt-narratives-about/46

2022-04-18 09:20 UTC, davidheyman commented
@buccalon This is ready for a full review. I'm sure you've seen the translation file here (src/hooks/useLocale.js) which will need fixing by a native speaker. Could you also check to make sure that none of the links have broken? I still need to add a link to switch between the languages but I'll figure out where that goes later.

2022-04-18 17:31 UTC, martimpassos requested changes

2022-04-18 19:06 UTC, buccalon commented on src/hooks/useLocale.js
> +    visuals: 'Mapas / Planos / Aerias',
Não deveria ser `Mapas / Projetos / Imagens Aéreas`?

2022-04-18 19:29 UTC, martimpassos commented on src/hooks/useLocale.js
> +    visuals: 'Mapas / Planos / Aerias',
Pode ser, eu tentei diferenciar só porque temos imagens aéreas em `Vistas` também. Em `Aerials` são só levantamentos aerofotogramétricos ou imagens de satélite...

2022-04-18 20:36 UTC, buccalon commented
@davidheyman Thanks for putting this together. Here is what I found:

## Issues

- An unauthenticated user gets 404 at https://narratives-pr-81.onrender.com/en/projects (after clicking in "Login")
- The profile picture and 'Manage My Narratives' button for authenticated users disappeared
- Sign Up page is not translated: https://narratives-pr-81.onrender.com/pt/signup
- Download my data is broken https://narratives-pr-81.onrender.com/download and [locale]/download
- Gallery link in the Portuguese Project panel leads to the English gallery (maybe automatic routing in my case)

- English-only title placeholder:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/476699/163870071-c809ed7e-4104-4534-bb2c-d4ba648560e7.png">

- English-only password emails:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/476699/163870526-ddc20214-ebd6-4f11-87c9-48ad1d633d87.png">

## Comments

- Let's ask users for their preferred language when they register?
- Let's have a language field for each narrative, so we can filter the gallery by language?

2022-05-03 15:35 UTC, davidheyman commented
@buccalon @martimpassos This is now ready for a final look and review. The big change is adding the additional translations around account management.

If we are getting close to your deadline, we can always merge this into master and then handle any outstanding changes there.

2022-05-03 15:54 UTC, martimpassos commented
I'm getting a "unverified account" error/warning when trying to login in this deployment, same credentials work fine in production

2022-05-03 19:02 UTC, buccalon commented
@davidheyman similar issue here. I tried to reset the password, but the action is not completed

<img width="716" alt="image" src="https://user-images.githubusercontent.com/476699/166524127-926e61e5-9b65-488e-a723-a2f0c7977d86.png">

2022-05-09 10:03 UTC, davidheyman commented
@martimpassos It's a different database for the dev version so you'll need to create a new account.

2022-05-09 10:05 UTC, davidheyman commented
@buccalon According to the database you did successfully reset your password. It's encrypted so I can't see what it is. Can you try again?

2022-05-09 13:16 UTC, martimpassos commented
@davidheyman I created an account on the dev database. Inputting the correct password gives me `You could not be logged in. Please check your username and password.` An incorrect password leads to `Your account has not been verified. Please check your email for a verification link.`

2022-05-09 18:46 UTC, buccalon commented
@davidheyman not working with my original dev account. I had to create another account by typing `/signup` in the URL, still, there was something wrong with the form's behavior. I can access the admin dashboard in with my original account on `/admin`

2022-06-01 18:00 UTC, buccalon commented
@davidheyman 
- Account verification is broken (I had to verify @martimpassos manually)
- Gallery: Old URLs without language path return 404
- Loading animation English-only
- Search results English-only
<img width="284" alt="image" src="https://user-images.githubusercontent.com/476699/171471505-2a004f08-b002-457e-ba7a-09c391b4bbb0.png">

2022-06-20 09:54 UTC, davidheyman commented
These issues should now be resolved and this is ready for another test.

With the account verification, the accounts were being verified a second time on the translation redirect so I've disabled the failure message for double verification.

2022-07-12 19:58 UTC, buccalon commented
Thanks, @davidheyman. This is what @martimpassos and I found:

## Issues

- Portuguese version has header menu in English
<img width="724" alt="image" src="https://user-images.githubusercontent.com/476699/178580647-324facf3-69ec-494b-a221-b61588b18775.png">

- Geographic layers are English-only and list two empty items
<img width="285" alt="image" src="https://user-images.githubusercontent.com/476699/178581168-e15731a6-3b2f-4095-95bf-f032fc13b5b7.png">

## Suggestions

We also felt that the language switch should be consistent across all imagineRio services (either header or footer).

## Comments

The only critical issue seems to be the English menu, so we agree in merging once it gets fixed.

2022-11-25 12:35 UTC, merged